spring:
  application:
    name: webapp
  profiles:
    active: dev

server:
  port: 9011
  servlet:
    session:
      timeout: 864000

logging:
  level:
    root: info

management:
  server:
    port: 9111
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,heapdump,sessions,httptrace,logfile

---
spring:
  profiles: dev

aws:
  lambda:
    schema: http
    host: localhost
    port: 9112

---
spring:
  profiles: aws-test

aws:
  lambda:
    schema: https
    host: localhost
    port: 9112

---
spring:
  profiles: aws-prod

aws:
  lambda:
    schema: https
    host: localhost
    port: 9112
