spring:
  application:
    name: webapp
  profiles:
    active: dev

server:
  port: 9011
  servlet:
    session:
      timeout: 864000

logging:
  level:
    root: info

management:
  server:
    port: 9112
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,heapdump,sessions,httptrace,logfile

---
spring:
  profiles: dev

aws:
  jlambda:
    schema: https
    host: unhxtazish.execute-api.eu-west-3.amazonaws.com
    port: 443
    path: /jlambda-test-stage/jlambda-test-api
  olalambda:
    schema: https
    host: unhxtazish.execute-api.eu-west-3.amazonaws.com
    port: 443
    path: /jlambda-test-stage/jlambda-test-api

---
spring:
  profiles: aws-test

aws:
  jlambda:
    schema: https
    host: unhxtazish.execute-api.eu-west-3.amazonaws.com
    port: 443
    path: /jlambda-test-stage/jlambda-test-api
  olalambda:
    schema: https
    host: unhxtazish.execute-api.eu-west-3.amazonaws.com
    port: 443
    path: /jlambda-test-stage/jlambda-test-api
---
spring:
  profiles: aws-prod

aws:
  jlambda:
    schema: https
    host: g7ga8rwyte.execute-api.eu-west-3.amazonaws.com
    port: 443
    path: /jlambda-test-stage/jlambda-test-api
  olalambda:
    schema: https
    host: unhxtazish.execute-api.eu-west-3.amazonaws.com
    port: 443
    path: /jlambda-test-stage/jlambda-test-api

